Models/Actor.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace eTickets.Models
{
	public class Actor
	{
        [Key]
        public int Id { get; set; }

        [Display(Name = "Foto")]
        public string? ProfilePictureURL { get; set; }

        [Display(Name = "Nome")]
        [Required(ErrorMessage = "O nome do ator é obrigatório.")]
        public string? FullName { get; set; }

        [Display(Name = "Biografia")]
        public string? Bio { get; set; }

        public List<Actor_Movie>? Actors_Movies { get; set;}
    }
}

Models/Actor_Movie.cs
namespace eTickets.Models
{
	public class Actor_Movie
	{
		public int MovieId { get; set; }
		public Movie? Movie { get; set; }

		public int ActorId { get; set; }
		public Actor? Actor { get; set; }
	}
}

Models/Cinema.cs
using System.ComponentModel.DataAnnotations;

namespace eTickets.Models
{
	public class Cinema
	{
        [Key]
		public int Id { get; set; }

        [Display(Name = "Logo")]
        public string? Logo { get; set; }

        [Display(Name = "Cinema")]
        public string? Name { get; set; }

        [Display(Name = "Descrição")]
        public string? Description { get; set; }

        public List<Movie>? Movies { get; set; }
    }
}

Models/ErrorViewModel.cs
namespace eTickets.Models
{
	public class ErrorViewModel
	{
		public string? RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

Models/Movie.cs
using eTickets.Data.Enums;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace eTickets.Models
{
    public class Movie
	{
		[Key]
        public int Id { get; set; }

        [Display(Name = "Filme")]
        public string? Name { get; set; }

        [Display(Name = "Descrição")]
        public string? Description { get; set; }

        [Display(Name = "Preço")]
        public double Price { get; set; }

        [Display(Name = "Imagem")]
        public string? ImageURL { get; set; }

        [Display(Name = "Data Inicio")]
        public DateTime StartDate { get; set; }

        [Display(Name = "Data Término")]
        public DateTime EndDate { get; set; }

        [Display(Name = "Gênero")]
        public MovieCategory MovieCategory { get; set; }

        public List<Actor_Movie>? Actors_Movies { get; set; }

        // Cinema
        public int CinemaId { get; set; }

        [ForeignKey("CinemaId")]
        public Cinema? Cinema { get; set; }

		// Producer
		public int ProducerId { get; set; }

		[ForeignKey("ProducerId")]
		public Producer? Producer { get; set; }
	}
}

Models/Producer.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace eTickets.Models
{
	public class Producer
	{
		[Key]
		public int Id { get; set; }

		[Display(Name = "Foto")]
		public string? ProfilePictureURL { get; set; }

		[Display(Name = "Nome")]
		public string? FullName { get; set; }

		[Display(Name = "Biografia")]
		public string? Bio { get; set; }

		public List<Movie>? Movies { get; set; }
	}
}

Controllers/ActorsController.cs
using eTickets.Data.Services;
using eTickets.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace eTickets.Controllers
{
	public class ActorsController : Controller
	{
		private readonly IActorsService _service;

        public ActorsController(IActorsService service)
        {
			_service = service;
        }
        public async Task<IActionResult> Index()
		{
			var actors = await _service.GetAll();
			return View(actors);
		}
		
		public IActionResult Create()
		{
			return View();
		}

		[HttpPost]
		public IActionResult Create([Bind("FullName, ProfilePictureURL, Bii")]Actor actor)
		{
			if (!ModelState.IsValid)
			{
				return View(actor);
			}
			_service.Add(actor);
			return RedirectToAction(nameof(System.Index));
		}
		
		//Get: Actors/Details/{id}
		public async Task<IActionResult> Details(int id)
		{
			var actor = await _service.GetByIdAsync(id);
			if (actor == null) return View("NotFound");
			return View(actor);
		}

		public async Task<IActionResult> Edit(int id)
		{
			var actor = await _service.GetByIdAsync(id);
			return View(actor);
		}

		[HttpPost]
		public async Task<IActionResult> Edit(int id, Actor actor)
		{
			if (!ModelState.IsValid) return View(actor);
			
			await _service.UpdateAsync(id, actor);
			return RedirectToAction(nameof(Index));
		}

		public async Task<IActionResult> Delete(int id)
		{
			var actor = await _service.GetByIdAsync(id);
			if (actor == null) return View("NotFound");

			return View(actor);
		}

		[HttpPost]
		public async Task<IActionResult> DeleteConfirmed(int id)
		{
			var actorToDelete = await _service.GetByIdAsync(id);
			if (actorToDelete == null) return View("NotFound");
			
			await _service.DeleteAsync(id);
			return RedirectToAction(nameof(Index));
		}
		
		
	}
}

Controllers/CinemasController.cs
using eTickets.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace eTickets.Controllers
{
	public class CinemasController : Controller
	{
		private readonly AppDbContext _context;
        public CinemasController(AppDbContext context)
        {
			_context = context;
        }
        public async Task<IActionResult> Index()
		{
			var cinemas = await _context.Cinemas.ToListAsync();
			return View(cinemas);
		}
	}
}

Controllers/MoviesController.cs
using eTickets.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace eTickets.Controllers
{
	public class MoviesController : Controller
	{
		private readonly AppDbContext _context;
        public MoviesController(AppDbContext context)
        {
			_context = context;
        }
        public async Task<IActionResult> Index()
		{
			var movies = await _context.Movies.Include(x => x.Cinema).ToListAsync();
			return View(movies);
		}
	}
}

Controllers/ProducersController.cs
using eTickets.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace eTickets.Controllers
{
	public class ProducersController : Controller
	{
		private readonly AppDbContext _context;

        public ProducersController(AppDbContext context)
        {
			_context = context;
        }
        public async Task<IActionResult> Index()
		{
			var producers = await _context.Producers.ToListAsync();
			return View(producers);
		}
	}
}

Views/Actors/Create.cshtml
@model Actor

@{
    ViewData["Title"] = "Adicionar novo ator";
}

<div class="row text">
    <div class="col-md-8 offset-2">
        <p>
            <h1>Adicionar Novo Ator</h1>
        </p>
        <div class="row">
            <div class="col-md-8 offset-2">
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                </form>
                <div class="mb-2 text-center">
                    <img id="ProfilePicturePreview" style="max-width: 250px;" />
                </div>
                <div class="mb-2">
                    <label asp-for="ProfilePictureURL" class="control-label"></label>
                    <input asp-for="ProfilePictureURL" class="form-control" />
                    <span asp-validation-for="ProfilePictureURL" class="text-danger"></span>
                </div>
                <div class="mb-2">
                    <label asp-for="FullName" class="control-label"></label>
                    <input asp-for="FullName" class="form-control" />
                    <span asp-validation-for="FullName" class="text-danger"></span>
                </div>
                <div class="mb-2">
                    <label asp-for="Bio" class="control-label"></label>
                    <input asp-for="Bio" class="form-control" />
                    <span asp-validation-for="Bio" class="text-danger"></span>
                </div>

                <div class="">
                    <input type="submit" value="Criar" class="btn btn-outline-success float-end" />
                    <a class="btn btn-outline-secondary" asp-action="Index">Ver todos</a>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script>
        $("#ProfilePictureURL").on("change", function() {
            var output = document.getElementById("ProfilePicturePreview");
            output.src = $(this).val();
        })
    </script>
}

Views/Actors/Delete.cshtml
@model Actor

@{
    ViewData["Title"] = "Deletar ator";
}

<div class="row text">
    <div class="col-md-8 offset-2">
        <p>
            <h1>Deseja deletar este ator?</h1>
        </p>
        <div class="row">
            <div class="col-md-8 offset-2">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="mb-2 text-center">
                        <img id="ProfilePicturePreview" style="max-width: 150px;"/>
                    </div>
                    <div class="mb-2">
                        <label asp-for="ProfilePictureURL" class="control-label"></label>
                        <input asp-for="ProfilePictureURL" class="form-control" readonly/>
                        <span asp-validation-for="ProfilePictureURL" class="text-danger"></span>
                    </div>
                    <div class="mb-2">
                        <label asp-for="FullName" class="control-label"></label>
                        <input asp-for="FullName" class="form-control" readonly/>
                        <span asp-validation-for="FullName" class="text-danger"></span>
                    </div>
                    <div class="mb-2">
                        <label asp-for="Bio" class="control-label"></label>
                        <input asp-for="Bio" class="form-control" readonly/>
                        <span asp-validation-for="Bio" class="text-danger"></span>
                    </div>

                    <div class="">
                        <form asp-action="DeleteConfirmed">
                            <input hidden asp-for="Id" />
                            <button class="btn btn-outline-danger float-end" type="submit">Deletar</button>
                        </form>
                        <a class="btn btn-outline-secondary" asp-action="Index">Voltar</a>
                    </div>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script>
    
    $(document).ready(function () {
        let output = document.getElementById("ProfilePicturePreview");
        output.src = $("#ProfilePictureURL").val();
    })
        
    </script>
}

Views/Actors/Details.cshtml
@model Actor

@{
    ViewData["Title"] = "Adicionar novo ator";
}

<div class="row text">
    <div class="col-md-8 offset-2">
        <p>
            <h1>Detalhes de @Model.FullName</h1>
        </p>
        <div class="row">
            <div class="col-md-8 offset-2">
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="mb-2 text-center">
                        <img id="ProfilePicturePreview" style="max-width: 150px;"/>
                    </div>
                    <div class="mb-2">
                        <label asp-for="ProfilePictureURL" class="control-label"></label>
                        <input asp-for="ProfilePictureURL" class="form-control" readonly/>
                        <span asp-validation-for="ProfilePictureURL" class="text-danger"></span>
                    </div>
                    <div class="mb-2">
                        <label asp-for="FullName" class="control-label"></label>
                        <input asp-for="FullName" class="form-control" readonly/>
                        <span asp-validation-for="FullName" class="text-danger"></span>
                    </div>
                    <div class="mb-2">
                        <label asp-for="Bio" class="control-label"></label>
                        <input asp-for="Bio" class="form-control" readonly/>
                        <span asp-validation-for="Bio" class="text-danger"></span>
                    </div>

                    <div class="">
                        <a class="btn btn-outline-success float-end" asp-action="Edit" asp-route-id="@Model.Id">Editar</a>
                        <a class="btn btn-outline-secondary" asp-action="Index">Ver todos</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script>
    
    $(document).ready(function () {
        let output = document.getElementById("ProfilePicturePreview");
        output.src = $("#ProfilePictureURL").val();
    })
        
    </script>
}

Views/Actors/Edit.cshtml
@model Actor

@{
    ViewData["Title"] = "Editar ator";
}

<div class="row text">
    <div class="col-md-8 offset-2">
        <p>
            <h1>Editar <strong>@Model.FullName</strong></h1>
        </p>
        <div class="row">
            <div class="col-md-8 offset-2">
                <form asp-action="Edit">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="mb-2 text-center">
                        <img id="ProfilePicturePreview" style="max-width: 150px;"/>
                    </div>
                    <div class="mb-2">
                        <label asp-for="ProfilePictureURL" class="control-label"></label>
                        <input asp-for="ProfilePictureURL" class="form-control"/>
                        <span asp-validation-for="ProfilePictureURL" class="text-danger"></span>
                    </div>
                    <div class="mb-2">
                        <label asp-for="FullName" class="control-label"></label>
                        <input asp-for="FullName" class="form-control"/>
                        <span asp-validation-for="FullName" class="text-danger"></span>
                    </div>
                    <div class="mb-2">
                        <label asp-for="Bio" class="control-label"></label>
                        <input asp-for="Bio" class="form-control"/>
                        <span asp-validation-for="Bio" class="text-danger"></span>
                    </div>

                    <div class="">
                        <input class="btn btn-outline-success float-end" type="submit">Salvar</input>
                        <a class="btn btn-outline-secondary" asp-action="Index">Voltar</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script>
    
    $(document).ready(function () {
        let output = document.getElementById("ProfilePicturePreview");
        output.src = $("#ProfilePictureURL").val();
    })
    
    $("#ProfilePictureURL").on("change", function() {
        let output = document.getElementById("ProfilePicturePreview");
        output.src = $(this).val();
    })
        
    </script>
}

Views/Actors/Index.cshtml
@model IEnumerable<Actor>

@{
    ViewData["Title"] = "Lista de Atores";
}

<div class="row">
    <div class="col-md-8 offset-md-2">

        <table class="table">
            <thead>
                <tr>
                    <th class="text-center">@Html.DisplayNameFor(model => model.ProfilePictureURL)</th>             
                    <th class="text-center">@Html.DisplayNameFor(model => model.FullName)</th>
                    <th class="text-center">@Html.DisplayNameFor(model => model.Bio)</th>
                    <th class="text-center">Ações</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr class="text-center">
                        <td class="align-middle">
                            <img class="rounded-circle"
                                 src="@item.ProfilePictureURL"
                                 alt="@item.FullName"
                                 style="width: 150px; height: 150px; object-fit: cover" />
                        </td>
                        <td class="align-middle">
                            @Html.DisplayFor(modelItem => item.FullName)
                        </td>
                        <td class="align-middle">
                            @Html.DisplayFor(modelItem => item.Bio)
                        </td>
                        <td class="align-middle">
                            <a class="btn btn-outline-primary" asp-action="Edit" asp-route-id="@item.Id">
                                <i class="bi bi-pencil-square"></i>Editar
                            </a>
                            <a class="btn btn-outline-info" asp-action="Details" asp-route-id="@item.Id">
                                <i class="bi bi-eye"></i>Detalhes
                            </a>
                            <a class="btn btn-outline-danger" value="@item.Id" asp-action="Delete" asp-route-id="@item.Id">
                                <i class="bi bi-trash"></i>Delete
                            </a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>

    </div>
</div>
<div style="position: fixed; bottom: 45px; left: 50%; transform: translate(-50%, 0); z-index: 1">
    <a asp-action="Create" class="btn btn-success">
        <i class="bi bi-plus-circle"></i> Adicionar Ator
    </a>
</div>

@* ### DELETE MODAL ### *@
<div class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Modal title</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Modal body text goes here.</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary">Save changes</button>
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

Views/Cinemas/Index.cshtml
@model IEnumerable<Cinema>
@{
    ViewData["Title"] = "Lista de Cinemas";
}

<div class="row">
    <div class="col-md-8 offset-md-2">
        <table class="table">
            <thead>
                <tr class="text-center">
                    <th class="text-certer">@Html.DisplayNameFor(model => model.Logo)</th>
                    <th class="text-certer">@Html.DisplayNameFor(model => model.Name)</th>
                    <th class="text-certer">@Html.DisplayNameFor(model => model.Description)</th>
                    <th class="text-certer">Ações</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr class="text-center">
                        <td class="text-center">
                            <img 
                                class="rounded-circle" 
                                src="@item.Logo" 
                                alt="@item.Name" 
                                style="max-width: 150px"
                            />
                        </td>
                        <td class="align-middle">
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td class="align-middle">@Html.DisplayFor(modelItem => item.Description)</td>
                        <td class="align-middle">
                            <a class="btn btn-outline-primary">
                                <i class="bi bi-pencil-square"></i>Editar
                            </a>
                            <a class="btn btn-outline-danger">
                                <i class="bi bi-trash"></i>Delete
                            </a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

Views/Movies/Index.cshtml
@using System.Globalization;
@model IEnumerable<Movie>
@{
    ViewData["Title"] = "Lista de Filmes";
}

<div class="row">
    @foreach (var item in Model)
    {
        <div class="col-md-4 col-xs-6 border-primary mb-3">
            <div class="card mb-3" style="max-width: 540px;">
                <div class="row g-0">
                    <div class="col-md-12">
                        <div class="card-header text-white bg-info">
                            <p class="card-text">
                                <h5 class="card-title">
                                    @item.Name
                                </h5>
                            </p>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <img src="@item.ImageURL" width="100%" alt="@item.Name">
                    </div>
                    <div class="col-md-6">
                        <div class="card-body">
                            <p class="card-text">@item.Description</p>
                            <p class="card-text"><b>Cinema: </b>@item.Cinema.Name</p>
                            <p class="card-text"><b>Category: </b>@item.MovieCategory</p>
                            <p class="card-text"><b>Start Date: </b>@item.StartDate.ToString("dd MMM yy")</p>
                            <p class="card-text"><b>End Date: </b>@item.EndDate.ToString("dd MMM yy")</p>
                            <p class="card-text ">
                                <b>Status: </b>
                                @if (DateTime.Now >= item.StartDate && DateTime.Now <= item.EndDate)
                                {
                                    <span class="badge bg-success text-white">AVAILABLE</span>
                                }
                                else if (DateTime.Now > item.EndDate)
                                {
                                    <span class="badge bg-danger text-white">EXPIRED</span>
                                }
                                else
                                {
                                    <span class="badge bg-primary text-white">UPCOMING</span>
                                }
                            </p>

                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="card-footer ">
                            <p class="card-text">
                                <a class="btn btn-outline-primary float-right" asp-action="" asp-route-id="@item.Id">
                                    <i class="bi bi-eye-fill"></i> Mais Detalhes
                                </a>
                                <a class="btn btn-success text-white @((DateTime.Now > item.EndDate) ? "disabled" : "")"
                               asp-controller=""
                               asp-action=""
                               asp-route-id="@item.Id">
                                    <i class="bi bi-cart-plus"></i> Adicionar ao carrinho (@string.Format(new CultureInfo("pt-BR"), "{0:C}", @item.Price))
                                </a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</div>

Views/Producers/Index.cshtml
@model IEnumerable<Producer>
@{
    ViewData["Title"] = "Lista de Produtores";
}

<div class="row">
    <div class="col-md-8 offset-md-2">
        <table class="table">
            <thead>
                <tr>
                    <th class="text-center">@Html.DisplayNameFor(model => model.ProfilePictureURL)</th>
                    <th class="text-center">@Html.DisplayNameFor(model => model.FullName)</th>
                    <th class="text-center">@Html.DisplayNameFor(model => model.Bio)</th>
                    <th class="text-center">Ações</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr class="text-center">
                        <td class="align-middle">
                            <img 
                                class="rounded-circle"
                                src="@item.ProfilePictureURL" 
                                alt="@item.FullName"
                                style="max-width: 150px" />
                        </td>
                        <td class="align-middle">
                            @Html.DisplayFor(modelItem => item.FullName)
                        </td>
                        <td class="align-middle">
                            @Html.DisplayFor(modelItem => item.Bio)
                        </td>
                        <td class="align-middle">
                            <a class="btn btn-outline-primary">
                                <i class="bi bi-pencil-square"></i>Editar
                            </a>
                            <a class="btn btn-outline-info">
                                <i class="bi bi-eye"></i>Detalhes
                            </a>
                            <a class="btn btn-outline-danger">
                                <i class="bi bi-trash"></i>Delete
                            </a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

Views/Shared/NotFound.cshtml
<div class="row">
    <div class="col-md text-center">
        <h1 class="text-info">Ocorreu um erro ao processar sua página.</h1>
        <a class="btn btn-primary" asp-controller="Movies" asp-action="Index">Voltar à página principal</a>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - eTickets</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/eTickets.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="d-flex w-75 ps-3">
                <a class="navbar-brand" asp-area="" asp-controller="Movies" asp-action="Index">eTickets</a>
                <a class="navbar-brand" asp-controller="Movies" asp-action="Index">
                    <i class="badge-info bi-film"></i>
                    Filmes
                </a>
                <div class="dropdown">
                    <button class="btn dropdown-toggle navbar-brand" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="badge-info bi-gear"></i>
                        Gerenciar
                    </button>
                    <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                        <li>
                            <a class="dropdown-item" asp-controller="Cinemas" asp-action="Index">
                                <i class="bi bi-camera-reels"></i>
                                Cinemas
                            </a>
                        </li>
                        <li>
                            <a class="dropdown-item" asp-controller="Producers" asp-action="Index">
                                <i class="bi bi-headset"></i>
                                Produtores
                            </a>
                        </li>
                        <li>
                            <a class="dropdown-item" asp-controller="Actors" asp-action="Index">
                                <i class="bi bi-person-square"></i>
                                Atores
                            </a>
                       </li>
                    </ul>
                </div>
            </div>
            <form class="form d-flex my-2 my-lg-0" asp-controller="Movies" asp-action="" style="padding-right: 25px">
                <input name="searchString" class="form-control" placeholder="Procurar filme" />
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">
                    <i class="bi bi-search"></i>
                </button>
            </form>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - eTickets
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>